### ISSUE TITLE
Is base64Encoder reusable?

### ISSUE THREAD

**Issue by swftvsn** [hapijs/b64#19]
Hi,

I have a service that returns json that contains an array of base64 encoded images. The conversion happens like this: 

```ts
const base64Encoder = new b64.Encoder()
for (const readStream of streamsFromDisk) {
  readStream.pipe(base64Encoder)
  // Pipe to response using streamstream https://www.npmjs.com/package/stream-stream or similar
}
```

Is it advisable to reuse the base64Encoder like that, or should I construct new instance for each stream? Example of this here:

```ts
for (const readStream of streamsFromDisk) {
  const base64Encoder = new b64.Encoder()
  readStream.pipe(base64Encoder)
  // Pipe to response using streamstream https://www.npmjs.com/package/stream-stream or similar
}
```
Which approach is correct?

**Comment by Marsup** [comment]
Both are technically correct, but I doubt you want to do the 1st version as the result would be completely random.

**Comment by swftvsn** [comment]
Thanks for confirming this! I have Java background, and there I can share stateless (hence thread safe) code between streams and I was unsure if I should do that here.

**Comment by Marsup** [comment]
It is safe to do so, you're just piping many streams into one, with data arriving from multiple sources with different timings into a single stream, you'll just get a single base64 string that's the image of that. It works, it is thread-safe, but it is certainly not what you functionally want.

**Comment by Marsup** [comment]
Remember that you're in an async programming language, piping doesn't actually write stuff, it just plugs streams together, so your for loop is not like write stream 1, then write stream 2, then write stream 3, ... it's write all the chunks of those streams simultaneously as fast as each can deliver.

**Comment by swftvsn** [comment]
Actually the streams are later written in sequence using this:
```ts
currentStream.once('end', function () {
  base64ImageStream.pipe(res, { end: false })
})
currentStream = base64ImageStream
```

So the code is from preparation phase, and the resulting stuff is json. (There are more streams containing the json array start, separators etc.) So effectively only one encoder is doing stuff at any given moment. It also seems to work correctly. The idea is not to store stuff to memory when streaming out multiple files as json array. (The stream chain does image manipulation using sharp and various other things, but never stores any files completely in memory.)
